services:
  # Inherit services from both Producer and Consumer services
  producer-service:
    extends:
      file: ./services/producer/docker-compose.producer.yml
      service: producer-service

  consumer-service:
    extends:
      file: ./services/consumer/docker-compose.consumer.yml
      service: consumer-service
    env_file:
      - ./services/consumer/.env

  kafka:
    extends:
      file: docker-compose.kafka.yml
      service: kafka

  zookeeper:
    container_name: event_driven_zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - event-driven-app-network

networks:
  event-driven-app-network:
    driver: bridge
