services:
  # Inherit services from both Producer and Consumer services
  producer-service:
    extends:
      file: services/producer/docker-compose.producer.yml
      service: producer-service

  # consumer-service:
  #   extends:
  #     file: docker-compose.consumer.yml
  #     service: consumer-service

  kafka:
    container_name: event_driven_kafka
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - event-driven-app-network

  zookeeper:
    container_name: event_driven_zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - event-driven-app-network

networks:
  event-driven-app-network:
    driver: bridge
