services:
  db:
    container_name: event_driven_db
    image: "postgres:15"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - event-driven-app-network
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./.scripts/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
        
  consumer-service:
    container_name: event_driven_consumer
    image: "event_driven_consumer:latest"
    build:
      context: .
    ports:
      - "7008:20001"
    env_file:
      - ./.env
    depends_on:
      # - kafka
      - db
    networks:
      - event-driven-app-network
    volumes:
      - ./:/app
    restart: always
    tty: true
    stdin_open: true

  redis:
    image: redis
    container_name: event_driven_redis
    networks:
      -  event-driven-app-network
    env_file:
      - ./.env
  
  celery:
    image: "event_driven_consumer:latest"
    env_file:
      - ./.env
    restart: always
    command: celery worker -A consumer -l info
    container_name: event_driven_celery
    depends_on:
      - consumer-service
      - db
      - redis
    networks:
      - event-driven-app-network
  
  celery_beat:
    image: "event_driven_consumer:latest"
    restart: always
    container_name: event_driven_celery_beat
    command: celery -A consumer beat l info
    networks:
      - event-driven-app-network
    env_file:
      - ./.env

networks:
  event-driven-app-network:
    driver: bridge
    external: true

volumes:
  pgdata: