services:
  db:
      container_name: event_driven_db
      image: "postgres:15"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      networks:
        - event-driven-app-network
      env_file:
        - ./.env
      volumes:
        - pgdata:/var/lib/postgresql/data
        - ./.scripts/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
        
  consumer-service:
    container_name: event_driven_consumer
    build:
      context: .
    tty: true
    ports:
      - "7008:20001"
    env_file:
      - ./.env
    depends_on:
      # - kafka
      - db
    networks:
      - event-driven-app-network
    volumes:
      - ./:/app

networks:
  event-driven-app-network:
    driver: bridge

volumes:
  pgdata: