#!/bin/bash

psql -v ON_ERROR_STOP=1 <<-EOSQL
   CREATE USER $SETTINGS_DB_USER WITH PASSWORD '$SETTINGS_DB_PASSWORD';
   CREATE DATABASE $SETTINGS_DB_NAME OWNER $SETTINGS_DB_USER;
   GRANT ALL PRIVILEGES ON DATABASE $SETTINGS_DB_NAME to $SETTINGS_DB_USER;
   ALTER ROLE $SETTINGS_DB_USER WITH LOGIN;
   ALTER ROLE $SETTINGS_DB_USER WITH CREATEDB;
EOSQL
